// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Fr9j71mkborBIIppB6ucfHpvDDb-43s',
    appId: '1:544390143898:web:b02c00b1f399c3323ce423',
    messagingSenderId: '544390143898',
    projectId: 'auth-system-593c3',
    authDomain: 'auth-system-593c3.firebaseapp.com',
    storageBucket: 'auth-system-593c3.firebasestorage.app',
    measurementId: 'G-TJLDC7JXMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpZN8eZqCfAtATObIg7mkHzLOclRkdEo',
    appId: '1:544390143898:android:2b99463755e0c5bc3ce423',
    messagingSenderId: '544390143898',
    projectId: 'auth-system-593c3',
    storageBucket: 'auth-system-593c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ug_Vn9E3078Q5DfH-OusQNhxGscUH4o',
    appId: ' 1:544390143898:ios:c7bd09a6ef50594f3ce423',
    messagingSenderId: '544390143898',
    projectId: 'auth-system-593c3',
    storageBucket: 'auth-system-593c3.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ug_Vn9E3078Q5DfH-OusQNhxGscUH4o',
    appId: '1:544390143898:ios:c7bd09a6ef50594f3ce423',
    messagingSenderId: '544390143898',
    projectId: 'auth-system-593c3',
    storageBucket: 'auth-system-593c3.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Fr9j71mkborBIIppB6ucfHpvDDb-43s',
    appId: '1:544390143898:web:8c823f936086e6bf3ce423',
    messagingSenderId: '544390143898',
    projectId: 'auth-system-593c3',
    authDomain: 'auth-system-593c3.firebaseapp.com',
    storageBucket: 'auth-system-593c3.firebasestorage.app',
    measurementId: 'G-0S8H83HDT0',
  );
}
